name: 'Docs-as-code with Confluence'
description: 'Publishes documentation (requires an MkDocs config) to Confluence'
branding:
  icon: 'book-open'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  confluence_tenant:
    description: 'Your Atlassian tenant name'
    required: true
  confluence_space:
    description: 'The key of the space to host your documentation'
    required: true
  confluence_user:
    description: 'The username used to authenticate with Confluence REST API'
    required: true
  confluence_token:
    description: 'The token used to authenticate with Confluence REST API'
    required: true
  confluence_parent_page:
    description: 'The title of an existing page to use as parent'
    required: false
  confluence_title_prefix:
    description: 'This prefix will be prepended to all confluence page titles'
    required: false
  confluence_force_update:
    description: 'When set to "yes" all pages will be published to confluence including unchanged'
    required: false
    default: 'no'
  kroki_enabled:
    description: 'When "yes" conversion of Mermaid & PlantUML graphs into images (png) using "kroki.io"'
    required: false
    default: 'yes'
  mermaid_renderer:
    description: ''
    required: false
  plantuml_renderer:
    description: ''
    required: false
